services:
  rasa:
    image: rasa-src-en
    ports:
      - 5006:5006

  appen:
    image: rasa-src-en-actionserver
    volumes:
      - ./actions:/app/actions
    ports:
      - 5056:5056
    command:
      - start
      - --actions
      - actions
      - -p 5056