# Extend the official Rasa SDK image
FROM rasa/rasa-sdk:3.0.6

WORKDIR /app

USER root

RUN pip install firebase_admin && \
    pip install pandas

# Copy actions folder to working directory
COPY ./actions /app/actions
COPY ./helper.py /app/
COPY *.json /app/

USER 1001