- intent: faq/ask_getTemplateApplication
  examples: |
    - How do I make an application request?
    - Do you have a secretary application form?
    - Is there a model application for the secretary?
    - Can you show me an application form?
    - Can you send me an application form?
    - Which is the application form?
    - I want you to send me an application form!
    - Give me an application form!

    