# Extend the official Rasa SDK image
FROM rasa/rasa-sdk:3.1.0

# Use subdirectory as working directory
WORKDIR /app

USER root

RUN pip install firebase_admin && \
    pip install pandas

# Copy actions folder to working directory
COPY ./actions /app/actions
COPY ./helper.py /app/
COPY *.json /app/

USER 1001