services:
  rasa:
    image: ancadavid/chatbot-polly:rasa-src-ro
    ports:
      - 5005:5005
    command:
      - run
  app:
    image: ancadavid/chatbot-polly:rasa-src-ro-actionserver
    expose: 
    - 5055


    